// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AuthProviderCreate(ctx context.Context, arg AuthProviderCreateParams) (int32, error)
	AuthProviderGetById(ctx context.Context, arg AuthProviderGetByIdParams) (AuthProvider, error)
	AuthProviderGetByProviderUserId(ctx context.Context, arg AuthProviderGetByProviderUserIdParams) (AuthProvider, error)
	AuthProviderGetByUserId(ctx context.Context, arg AuthProviderGetByUserIdParams) (AuthProvider, error)
	// refresh_token = COALESCE($2, refresh_token),
	AuthProviderUpdateTokens(ctx context.Context, arg AuthProviderUpdateTokensParams) (int64, error)
	AuthSessionActiveCount(ctx context.Context, userID int32) (int64, error)
	AuthSessionActiveGet(ctx context.Context, userID int32) ([]AuthSession, error)
	AuthSessionCreate(ctx context.Context, userID int32) (AuthSession, error)
	AuthSessionGet(ctx context.Context, token string) (AuthSession, error)
	AuthSessionGetOwner(ctx context.Context, token string) (AuthSessionGetOwnerRow, error)
	AuthSessionValidate(ctx context.Context, token string) (AuthSessionStatus, error)
	DefaultBroadcasterGet(ctx context.Context) (TwitchDefaultBroadcaster, error)
	DefaultBroadcasterUpdate(ctx context.Context, twitchUserID string) (int64, error)
	TwitchDefaultBotGet(ctx context.Context) (TwitchDefaultBot, error)
	TwitchDefaultBotUpdate(ctx context.Context, twitchUserID string) (int64, error)
	TwitchUserConnectProvider(ctx context.Context, arg TwitchUserConnectProviderParams) (int64, error)
	TwitchUserCreate(ctx context.Context, arg TwitchUserCreateParams) (string, error)
	UserCreate(ctx context.Context) (int32, error)
	UserDelete(ctx context.Context, id int32) (int64, error)
	UserGetById(ctx context.Context, id int32) (User, error)
	UserUpdate(ctx context.Context, arg UserUpdateParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
