// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: twitch.default-broadcaster.sql

package db

import (
	"context"
)

const twitchDefaultBroadcasterGet = `-- name: TwitchDefaultBroadcasterGet :one
SELECT
    broadcaster_id
FROM
    twitch.default_broadcaster
WHERE
    main = TRUE
`

func (q *Queries) TwitchDefaultBroadcasterGet(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, twitchDefaultBroadcasterGet)
	var broadcaster_id string
	err := row.Scan(&broadcaster_id)
	return broadcaster_id, err
}

const twitchDefaultBroadcasterUpdate = `-- name: TwitchDefaultBroadcasterUpdate :one
INSERT INTO twitch.default_broadcaster (main, broadcaster_id)
    VALUES (TRUE, $1)
ON CONFLICT (main)
    DO UPDATE SET
        broadcaster_id = $1
    RETURNING
        broadcaster_id
`

func (q *Queries) TwitchDefaultBroadcasterUpdate(ctx context.Context, broadcasterID string) (string, error) {
	row := q.db.QueryRow(ctx, twitchDefaultBroadcasterUpdate, broadcasterID)
	var broadcaster_id string
	err := row.Scan(&broadcaster_id)
	return broadcaster_id, err
}
