// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: twitch.default-bot.sql

package db

import (
	"context"
)

const twitchDefaultBotGet = `-- name: TwitchDefaultBotGet :one
SELECT main, twitch_user_id
FROM twitch.default_bot
WHERE main = true
`

func (q *Queries) TwitchDefaultBotGet(ctx context.Context) (TwitchDefaultBot, error) {
	row := q.db.QueryRow(ctx, twitchDefaultBotGet)
	var i TwitchDefaultBot
	err := row.Scan(&i.Main, &i.TwitchUserID)
	return i, err
}

const twitchDefaultBotUpdate = `-- name: TwitchDefaultBotUpdate :execrows
INSERT INTO twitch.default_bot (main, twitch_user_id)
VALUES (true, $1)
ON CONFLICT (main) DO UPDATE
  SET twitch_user_id = $1
`

func (q *Queries) TwitchDefaultBotUpdate(ctx context.Context, twitchUserID string) (int64, error) {
	result, err := q.db.Exec(ctx, twitchDefaultBotUpdate, twitchUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
